# Generated by Django 3.1.4 on 2021-01-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('code_major', models.CharField(max_length=20)),
                ('lecturer', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='First_App.lesson')),
            ],
        ),
    ]
