# Generated by Django 3.1.4 on 2021-01-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0002_auto_20210107_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
