# Generated by Django 3.1.4 on 2021-01-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0003_lesson_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='url_image',
            field=models.ManyToManyField(to='First_App.Student'),
        ),
    ]
