# Generated by Django 3.1.4 on 2021-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0006_auto_20210107_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_attend',
            field=models.BooleanField(default=False),
        ),
    ]
