# Generated by Django 3.1.4 on 2021-01-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0008_auto_20210107_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url_image',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='First_App.Student'),
        ),
    ]
