# Generated by Django 3.1.4 on 2021-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0009_auto_20210107_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studentImage'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attend',
            field=models.ManyToManyField(blank=True, null=True, to='First_App.Attendent'),
        ),
    ]
