# Generated by Django 3.1.5 on 2021-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0010_auto_20210107_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attend',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attend',
            field=models.ManyToManyField(blank=True, to='First_App.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='attends',
            field=models.ManyToManyField(blank=True, to='First_App.Attendent'),
        ),
        migrations.AlterField(
            model_name='attendent',
            name='date',
            field=models.DateField(),
        ),
    ]
