# Generated by Django 3.1.5 on 2021-01-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0011_auto_20210108_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attends',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='attend',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attend',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='First_App.attendent'),
        ),
    ]
