# Generated by Django 3.1.5 on 2021-01-08 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0012_auto_20210108_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='attendent',
            name='is_attend',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='attend',
        ),
        migrations.AddField(
            model_name='attendent',
            name='code_course',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendent',
            name='code_student',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendent',
            name='url_image',
            field=models.URLField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
