# Generated by Django 3.1.5 on 2021-01-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0014_auto_20210108_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendent',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='studentImage'),
        ),
    ]
