# Generated by Django 3.1.5 on 2021-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0015_auto_20210108_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendent',
            name='url_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
