# Generated by Django 3.1.5 on 2021-01-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0020_auto_20210124_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendent',
            name='code_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
