# Generated by Django 3.1.5 on 2021-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0021_auto_20210124_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendent',
            name='check_inf',
            field=models.BooleanField(default=False),
        ),
    ]
