# Generated by Django 3.1.5 on 2021-02-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0022_attendent_check_inf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendent',
            new_name='Attendance',
        ),
    ]
