# Generated by Django 3.1.5 on 2021-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0023_auto_20210223_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
